name: Deploy MERN Chatbot to AWS EC2 and S3

on:
  push:
    branches:
      - main

# Permissions needed for AWS OIDC authentication and ECR/S3 access
permissions:
  id-token: write
  contents: read

jobs:
  #######################################
  #        DEPLOY FRONTEND TO S3        #
  #######################################
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or your preferred version

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy Frontend to S3
        run: |
          aws s3 sync frontend/build/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete

  #######################################
  #        DEPLOY BACKEND TO EC2        #
  #######################################
  deploy-backend:
    runs-on: ubuntu-latest
    needs: deploy-frontend # Optional: run after frontend deployment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name of Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Backend Image to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f dockerfilebackend .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Deploy to EC2 via SSM Run Command
        env:
          IMAGE_URI: ${{ steps.build-image.outputs.image }}
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.AWS_EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploying backend container from $IMAGE_URI" \
            --parameters 'commands= \
              [ \
                "#!/bin/bash", \
                "cd /home/ubuntu", \
                "# Log in to ECR", \
                "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}", \
                "# Stop and remove the old container if it exists", \
                "docker stop mern-chatbot-backend || true", \
                "docker rm mern-chatbot-backend || true", \
                "# Pull the new image", \
                "docker pull ${{ steps.build-image.outputs.image }}", \
                "# Run the new container", \
                "docker run -d --name mern-chatbot-backend -p 80:5000 --restart always ${{ steps.build-image.outputs.image }}" \
              ] \
            '
